version: 0.2
env:
  variables:
    application: "kong"
    version: "1.3.0"
    account: "735655096069"
    region: "ap-southeast-2"
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t ${application}:${version} .
      - docker tag ${application}:${version} ${account}.dkr.ecr.${region}.amazonaws.com/${application}:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push ${version} Docker images to ECR...
      - docker push ${account}.dkr.ecr.${region}.amazonaws.com/${application}:${version}
